const weatherIconClassMap = {
  0: 'wi-tornado',
  1: 'wi-lightning',
  2: 'wi-lightning',
  3: 'wi-lightning',
  4: 'wi-lightning',
  5: 'wi-hail',
  6: 'wi-hail',
  7: 'wi-hail',
  8: 'wi-hail',
  9: 'wi-hail',
  10: 'wi-rain',
  11: 'wi-rain',
  12: 'wi-rain',
  13: 'wi-rain',
  14: 'wi-rain',
  15: 'wi-snow',
  16: 'wi-snow',
  17: 'wi-snow',
  18: 'wi-snow',
  19: 'wi-snow',
  20: 'wi-cloudy',
  21: 'wi-cloudy',
  22: 'wi-cloudy',
  23: 'wi-cloudy',
  24: 'wi-cloudy',
  25: 'wi-cloudy',
  26: 'wi-cloudy',
  27: 'wi-cloudy',
  28: 'wi-cloudy',
  29: 'wi-cloudy',
  30: 'wi-cloudy',
  31: 'wi-day-sunny',
  32: 'wi-day-sunny',
  33: 'wi-moonrise',
  34: 'wi-sunrise',
  35: 'wi-night-alt-hail',
  36: 'wi-hot',
  37: 'wi-night-rain',
  38: 'wi-night-rain',
  39: 'wi-night-rain',
  40: 'wi-night-rain',
  41: 'wi-night-snow',
  42: 'wi-night-snow',
  43: 'wi-night-snow',
  44: 'wi-day-cloudy-windy',
  45: 'wi-day-lightning',
  46: 'wi-day-lightning',
  47: 'wi-day-lightning',
  3200: 'wi-day-sunny',
};

const getWeatherIconClass = (code: string = '3200') => weatherIconClassMap[code];

export default getWeatherIconClass;
