const weatherIconMap = {
  0: 'Tornado.svg',
  1: 'Cloud-Lightning.svg',
  2: 'Cloud-Lightning.svg',
  3: 'Cloud-Lightning.svg',
  4: 'Cloud-Lightning.svg',
  5: 'Cloud-Hail.svg',
  6: 'Cloud-Hail.svg',
  7: 'Cloud-Hail.svg',
  8: 'Cloud-Hail.svg',
  9: 'Cloud-Hail.svg',
  10: 'Cloud-Rain.svg',
  11: 'Cloud-Rain.svg',
  12: 'Cloud-Rain.svg',
  13: 'Cloud-Rain.svg',
  14: 'Cloud-Rain.svg',
  15: 'Cloud-Snow.svg',
  16: 'Cloud-Snow.svg',
  17: 'Cloud-Snow.svg',
  18: 'Cloud-Snow.svg',
  19: 'Cloud-Snow.svg',
  20: 'Cloud.svg',
  21: 'Cloud.svg',
  22: 'Cloud.svg',
  23: 'Cloud.svg',
  24: 'Cloud.svg',
  25: 'Cloud.svg',
  26: 'Cloud.svg',
  27: 'Cloud.svg',
  28: 'Cloud.svg',
  29: 'Cloud.svg',
  30: 'Cloud.svg',
  31: 'Sun.svg',
  32: 'Sun.svg',
  33: 'Moon.svg',
  34: 'Sunrise.svg',
  35: 'Cloud-Hail-Moon.svg',
  36: 'Thermometer-75.svg',
  37: 'Cloud-Rain-Moon.svg',
  38: 'Cloud-Rain-Moon.svg',
  39: 'Cloud-Rain-Moon.svg',
  40: 'Cloud-Rain-Moon.svg',
  41: 'Cloud-Snow-Moon.svg',
  42: 'Cloud-Snow-Moon.svg',
  43: 'Cloud-Snow-Moon.svg',
  44: 'Cloud-Wind-Sun.svg',
  45: 'Clour-Ligntning.svg',
  46: 'Clour-Ligntning.svg',
  47: 'Clour-Ligntning.svg',
  3200: 'Sun.svg',
};

const getWeatherIcon = (code: string = '3200', path: string = '/static/svg/') => `${path}${weatherIconMap[code]}`;

export default getWeatherIcon;
